vscode:
  extensions:
    - "github.github-vscode-theme"
    - "equinusocio.vsc-material-theme-icons"
    - "albert.tabout"
    - "pinage404.bash-extension-pack"
    - "timonwong.shellcheck"
tasks:
  - name: install bashly
    command: |
      brew install bash
      brew install brew-gem
      brew gem install bashly
      bashly completions --install
  - name: install gum
    command: brew install gum