vscode:
  extensions:
    - "github.github-vscode-theme"
    - "equinusocio.vsc-material-theme-icons"
    - "albert.tabout"
    - "formulahendry.code-runner"
    - "catppuccin.catppuccin-vsc"
    - "catppuccin.catppuccin-vsc-icons"

tasks:
  - command: go install github.com/spf13/cobra-cli@latest
  - command: go install
  - command: cls
  