vscode:
  extensions:
    - "github.github-vscode-theme"
    - "equinusocio.vsc-material-theme-icons"
    - "albert.tabout"
    - "pinage404.bash-extension-pack"
    - "timonwong.shellcheck"
tasks:
  - name: install urfave/cli with go
    command: |
      go get github.com/urfave/cli/v2
  - name: install bubbletea
    command: go get github.com/charmbracelet/bubbletea
  - command: cd src/
  - command: cls
  