builds:
  - binary: seraphim-cli
    goos:
      - windows 
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
archives:
  - format: binary
release:
  prerelease: auto

universal_binaries:
  - replace: true
